### ISSUE TITLE
WhoScored Scraper

### ISSUE THREAD

**Issue by hedonistrh** [oseymour/ScraperFC#11]
Hey @oseymour , if I remember correctly we had scraper for _WhoScored_ and looks like that is not in the package anymore. I had some codes for that and I tried to run after update and now it is broken. 🤔 Are there any reason to remove that like _infringe_ or something else?

_Ps. https://github.com/probberechts/soccerdata providing scraper for that so maybe _infringe_ is not a problem. 🤔_

**Comment by oseymour** [comment]
Hey Halil! Yeah Stats Perform reached out to me with a cease and desist as they believe that scraping their data from WhoScored and FotMob is illegal. So I removed the module.

**Comment by hedonistrh** [comment]
Oh, gotcha. I knew _FotMob_ but not the _WhoScored_. Thanks for sharing that.

**Comment by oseymour** [comment]
Yeah, they asked me to remove both modules. And I don't have the time, energy, or money to challenge them on it.

**Comment by hedonistrh** [comment]
Yea, that makes perfect sense. I am afraid that https://github.com/probberechts/soccerdata can also have same issue. Actually it is failing with _WhoScored_ for most cases currently so I do not know will they act or not. 🤷
