### ISSUE TITLE
Making Repo Compatible with Selenium v4.3.0

### ISSUE THREAD

**Issue by hedonistrh** [oseymour/ScraperFC#12]
Hey @oseymour, [with latest version of Selenium](https://github.com/SeleniumHQ/selenium/blob/a4995e2c096239b42c373f26498a6c9bb4f2b3e7/py/CHANGES), there are significant changes. Especially following one is quite significant

`Deprecated find_element_by_* and find_elements_by_* are now removed (#10712)`

I also realized that from [this stack-overflow answer](https://stackoverflow.com/a/72773269). If one do not update _Selenium_ into new version, nothing is broken, but probably people will switch to that. One of the failing is happening [here](https://github.com/oseymour/ScraperFC/blob/main/build/lib/ScraperFC/FBRef.py#L86) for instance. Possible fix is, replacing that with
```python
for element in self.driver.find_elements("link text", season):
```

I am not sure how much time you have for those changes though. But if you would like, I can try to bring PR for that within next days. (At least for some of modules)

**Comment by oseymour** [comment]
Yes. I'm aware of all this. I've been changing them as I find them for a few months now. Probably missed a couple. Feel free to send any PRs and I'll get to them when I have time. Probably won't be a few weeks.

**Comment by hedonistrh** [comment]
Sure. Thanks for the answer. I'll do that probably within few days. Just need to be sure that nothing is broken. 🙏

**Comment by oseymour** [comment]
I went through all modules and Ctrl+F'ed for find_element_by* and find_elements_by*. All were changed to be compatible with Selenium 4.

**Comment by hedonistrh** [comment]
Thanks. 🙏🏼
