### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split' in scrape_shot_xy

### ISSUE THREAD

**Issue by aegonwolf** [oseymour/ScraperFC#16]
Module: Understat

Description of problem:
trying to scrape using Understat.scrape_shot_xy() I get an error.

Code:

`shot_xy = understat.scrape_shot_xy(year=2023, league='EPL')`

Error message:
```
File "Understat.py", line 971, in scrape_shot_xy
    match_id = link.split("/")[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```

I am guessing  a certain match_id does not exist.

**Comment by oseymour** [comment]
Hey @aegonwolf sorry I never commented on this. I see and it's been on my to-do list. I've been busy, sorry. I think this may have the same root cause as #17.

**Comment by oseymour** [comment]
Hey @aegonwolf I just ran the scrape_shot_xy() function for the 2022/23 PL season and it worked. What version of ScraperFC and Selenium do you have?

**Comment by oseymour** [comment]
v2.3.0 should fix this. Give it a go and let me know if you have any problems!

**Comment by aegonwolf** [comment]
awesome, thanks, I'll update the package!
