### ISSUE TITLE
Cannot scrape match data

### ISSUE THREAD

**Issue by nyaosimogaka** [oseymour/ScraperFC#18]
I am trying to scrape data from this [link](https://fbref.com/en/matches/1b2886ce/Qatar-Ecuador-November-20-2022-World-Cup).

I import the required packages `import ScraperFC as sfc` and `import traceback`. I then successfully initialize the scraper using `scraper = sfc.FBRef()`. 

After assigning the link using `link = https://fbref.com/en/matches/`, then comes the error.  When I run `match = scraper.scrape_match(link=link)` it gives the error 

[WDM] - Downloading: 100%|██████████| 6.46M/6.46M [00:14<00:00, 465kB/s]
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Temp\ipykernel_6748\635160529.py", line 9, in <module>
    match = scraper.scrape_match(link=link)
  File "C:\Users\User\anaconda3\lib\site-packages\ScraperFC\FBRef.py", line 468, in scrape_match
    matchweek = int(
ValueError: invalid literal for int() with base 10: 'group stage'

**Comment by oseymour** [comment]
Hey @nyaosimogaka! Thanks for raising this issue! I should be able to push a fix for this tonight or tomorrow.

**Comment by oseymour** [comment]
@nyaosimogaka This issue should be fixed in the most recent commits to this repo and in v2.5.0 on PyPI. Let me know if it isn't working for you!
