### ISSUE TITLE
TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'

### ISSUE THREAD

**Issue by NADoebler** [oseymour/ScraperFC#19]
Question:
When trying to initiate the FBref class, I get the following error: 

TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'

I have Selenium Version 4.8 installed.

**Comment by oseymour** [comment]
Hey @NADoebler! Can you give me some more info? Is this your first time using ScraperFC or have you been able to use it successfully in the past? Are you running it on a local or remote machine? Any details you can provide will help me troubleshoot this.

**Comment by NADoebler** [comment]
Thanks for reaching back. I am running it locally, and have used it sucessfully in the past.

**Comment by oseymour** [comment]
@NADoebler did you find a fix for this? Sorry I didn't reach back out. I had no clue what could be going wrong.

**Comment by PascalCeccaldi** [comment]
I had the same issue with Selenium 3.x 
Issue solved with clean environment + Selenium 4.9.0.

**Comment by oseymour** [comment]
Hey @PascalCeccaldi! Yeah I thought this "service argument" error was a Selenium 3 issue. But @NADoebler said they were on Selenium 4.8. I'm going to close this issue for now. Feel free to re-open in the future!
