### ISSUE TITLE
Bug Related with the Week when not all game is played

### ISSUE THREAD

**Issue by hedonistrh** [oseymour/ScraperFC#2]
Hey, currently I am trying to scrape matches of EPL 2021 with the following code
```python
import ScraperFC as sfc
scraper_understat = sfc.Understat()
matches = scraper_understat.scrape_matches(year=2022, league="EPL")
```
However, this raise an exception. When I try to debug with the logging of links via source code, I realized that one of the "url" is None. Then I just trace back how we get that data and it is coming from [here](https://understat.com/league/EPL/2021). Main reason of the exception is Wolves vs City match has not started. (AFAIK, that is postponed because of FA cup game) ⏳ 

I think that is kind of small issue and can gone when _**Understat**_ change that page. However, instead of raising an Exception maybe there can be some logging message and process can continue. Just as an idea but not sure that is the best way or not. 🙇 

![image](https://user-images.githubusercontent.com/34948815/163725237-b393e9e6-d052-4ea9-92eb-589c0c54ca01.png)

**Comment by oseymour** [comment]
This is a known issue. I was only worried about previous seasons when I wrote the code for this module. I'll put this at the top of the to-do list for when I get some time to work on ScraperFC. Thanks for bringing it up!

**Comment by hedonistrh** [comment]
Thanks a lot. I'll also try to look that if I have enough time. Thanks for effort. 🙏

**Comment by oseymour** [comment]
I just pushed a fix for this! Give it a go and let me know if it works for you.

**Comment by hedonistrh** [comment]
Hey @oseymour, I tried with **_1.11.2_** and it failed as expected. Then tried with _**1.11.5**_ and now it has no issue at all. Thanks a lot for the quick fix. 🙏
