### ISSUE TITLE
Transfermarkt data not scraping

### ISSUE THREAD

**Issue by c0neill96** [oseymour/ScraperFC#20]
Question:
Hi,

I cannot seem to scrape transfermarkt data. Running the below results in TypeError: cannot unpack non-iterable NoneType object. The issue appears to stem from the check_seasons() function

import ScraperFC as sfc
from ScraperFC.shared_functions import *

sfc.Transfermarkt().get_club_links(year=2014, league='Bundesliga')

**Comment by oseymour** [comment]
Hey @c0neill96! I'll look into it when I get some free time. Thanks for flagging this!

**Comment by oseymour** [comment]
@c0neill96 this should be fixed in the most recent push to the repo and in v2.6.3 on PyPI. Please re-open this issue if it's not working for you after updating! Thanks!
