### ISSUE TITLE
Incomplete data scrape_match() in FBRef() class

### ISSUE THREAD

**Issue by danirssx** [oseymour/ScraperFC#29]
Question: Hello! I'm utilizing the FBRef() class and its scrape_match() function. Everything seems to be functioning well, except for the 'Shots' data retrieval. I'm unsure whether I'm making any errors. For instance, here's the match I'm currently working with: https://fbref.com/en/matches/b476327d/Netherlands-South-Africa-August-6-2023-FIFA-Womens-World-Cup

![image](https://github.com/oseymour/ScraperFC/assets/98921448/18ac8bc7-430b-4cb3-b34c-8c822d7b0a39)

This is all the data that returns when it comes to 'Both'

**Comment by oseymour** [comment]
I scraped this match and it worked for me. Can you tell me:
* What OS are you on?
* What version of ScraperFC are you using?
* What version of Selenium do you have installed?
* Does this happen every time if you run it a few times?

**Comment by danirssx** [comment]
Now works!
