### ISSUE TITLE
Transfermarkt Scraper - Error "NonType object has no attribute 'getText'.

### ISSUE THREAD

**Issue by LucaPass1** [oseymour/ScraperFC#31]
Question: 

![ScraperFC error](https://github.com/oseymour/ScraperFC/assets/145138466/cd918a9f-dd05-4cf0-992e-3caff137e379)

**Comment by oseymour** [comment]
@LucaPass1 what version of ScraperFC do you have? I just scraped all of the 2022 Eredevisie players without any errors.
