### ISSUE TITLE
Understat Scraping Issue

### ISSUE THREAD

**Issue by isoadn** [oseymour/ScraperFC#36]
Question:
I was trying to pull the league tables for the 2024 season off of Understat and I was given this error:
![image](https://github.com/oseymour/ScraperFC/assets/59630004/f771bfbc-ce2f-4c0d-bb45-52c588a07ffb)

**Comment by oseymour** [comment]
Hey @isoadn, thanks for raising this! I don't have much time for ScraperFC right now but I'll fix this when I do!

**Comment by oseymour** [comment]
@isoadn This should be fixed in v3.0.0 so I'm closing this. Please re-open this if you're still getting this error!
