### ISSUE TITLE
Understat dataframe.append deprecated

### ISSUE THREAD

**Issue by rubeenvm2** [oseymour/ScraperFC#40]
From Understat.py:
634             game_states = game_states.append(
    635                 pd.DataFrame(row_array.reshape(1,-1)),#, columns=game_states.columns),
    636                 ignore_index=True
    637             )
Being game_states a df, I think append is deprecated in pandas, should be changed to concat().

**Comment by oseymour** [comment]
Hey @rubeenvm2! Thanks for raising this. I haven't fixed these in the past because the deprecation hadn't become effective. I don't have any time for ScraperFC right now, I'm working on other projects/life things. I'll update the append() calls to concat() when I get back to ScraperFC though!

**Comment by oseymour** [comment]
Following up on this: this would be a good community contribution, if somebody wanted to go through and fix these

**Comment by oseymour** [comment]
Updated in v3.0.0.
