### ISSUE TITLE
Sofascore get_players_match_stats issue

### ISSUE THREAD

**Issue by jmcala** [oseymour/ScraperFC#44]
Question:
Recently, while trying the get_players_match_stats function in Sofascore.py, the output returns only in 10 rows, meaning stats for only 10 players from each team. I tried this function previously and it worked just fine, seems like something changed but can´t figure it out. When inspecting the api link to the function request it shows data for all players, the issue appears when the function scrapes the data. 

Anyone has the same problem or any solution on why it only returns 10 rows?

Thanks!

**Comment by oseymour** [comment]
Hey @jmcala! SofaScore made some changes and are sending slightly modified results when scraping vs. browsing. I'm guessing this is tied to that. There are some fixes bouncing around and we'll be sure to test this.

**Comment by oseymour** [comment]
Should be fixed in v3.0.0. Please re-open if it's not!
