### ISSUE TITLE
Request error from Sofascore url scrape

### ISSUE THREAD

**Issue by yssefunc** [oseymour/ScraperFC#48]
I am getting error when I read the data sofascore url... I did not get before. It worked very well. But, today, i encounter this error. I think that it is libray issues. 

Traceback (most recent call last):
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus\request_decorator.py", line 110, in run_task
    result = func(reqs, data)
             ^^^^^^^^^^^^^^^^
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\ScraperFC\sofascore.py", line 46, in _botasaurus_get
    response = request.get(url)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus_requests\request_class.py", line 60, in get
    return reqs.get(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus_requests\reqs.py", line 346, in get
    return _get(url, *args, **add_redirects(kwargs, True))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus_requests\reqs.py", line 248, in request
    req.send()
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus_requests\reqs.py", line 135, in send
    raise e
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus_requests\reqs.py", line 132, in send
    self.response = self.session.request(self.method, self.url, **merged_kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus_requests\session.py", line 192, in request
    proc.send()
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus_requests\response.py", line 64, in send
    self.response = self.execute_request()
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus_requests\response.py", line 76, in execute_request
    raise e
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus_requests\response.py", line 69, in execute_request
    resp = self.session.execute_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus_requests\client.py", line 492, in execute_request
    return self.build_response(url, headers, response_object, request_payload['proxyUrl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus_requests\client.py", line 455, in build_response
    return self.build_response_obj(url, headers, response_object['response'], proxy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TCYSEFUNC\AppData\Local\anaconda3\Lib\site-packages\botasaurus_requests\client.py", line 435, in build_response_obj
    raise ClientException(response_object['body'])
botasaurus_requests.exceptions.ClientException: failed to do request: Get "https://api.sofascore.com/api/v1/event/12436980/statistics": read tcp 192.168.1.7:51445->146.75.119.52:443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by oseymour** [comment]
Hey @yssefunc! I'll take a look at this. What happens if you open that link in your web browser? Does it display the JSON data?

**Comment by yssefunc** [comment]
Hi again,
When i open the link, i get below json files.. 
{"statistics":[{"period":"ALL","groups":[{"groupName":"Match overview","statisticsItems":[{"name":"Ball possession","home":"53%","away":"47%","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":53,"awayValue":47,"renderType":2,"key":"ballPossession"},{"name":"Expected goals","home":"0.85","away":"2.19","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0.85,"awayValue":2.19,"renderType":1,"key":"expectedGoals"},{"name":"Big chances","home":"0","away":"5","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0,"awayValue":5,"renderType":1,"key":"bigChanceCreated"},{"name":"Total shots","home":"15","away":"12","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":15,"awayValue":12,"renderType":1,"key":"totalShotsOnGoal"},{"name":"Goalkeeper saves","home":"2","away":"7","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":2,"awayValue":7,"renderType":1,"key":"goalkeeperSaves"},{"name":"Corner kicks","home":"6","away":"5","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":6,"awayValue":5,"renderType":1,"key":"cornerKicks"},{"name":"Fouls","home":"17","away":"9","compareCode":1,"statisticsType":"negative","valueType":"event","homeValue":17,"awayValue":9,"renderType":1,"key":"fouls"},{"name":"Passes","home":"498","away":"454","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":498,"awayValue":454,"renderType":1,"key":"passes"},{"name":"Tackles","home":"16","away":"19","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":16,"awayValue":19,"renderType":1,"key":"totalTackle"},{"name":"Free kicks","home":"9","away":"17","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":9,"awayValue":17,"renderType":1,"key":"freeKicks"},{"name":"Yellow cards","home":"5","away":"2","compareCode":1,"statisticsType":"negative","valueType":"event","homeValue":5,"awayValue":2,"renderType":1,"key":"yellowCards"}]},{"groupName":"Shots","statisticsItems":[{"name":"Total shots","home":"15","away":"12","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":15,"awayValue":12,"renderType":1,"key":"totalShotsOnGoal"},{"name":"Shots on target","home":"7","away":"5","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":7,"awayValue":5,"renderType":1,"key":"shotsOnGoal"},{"name":"Hit woodwork","home":"0","away":"0","compareCode":3,"statisticsType":"negative","valueType":"event","homeValue":0,"awayValue":0,"renderType":1,"key":"hitWoodwork"},{"name":"Shots off target","home":"3","away":"4","compareCode":2,"statisticsType":"negative","valueType":"event","homeValue":3,"awayValue":4,"renderType":1,"key":"shotsOffGoal"},{"name":"Blocked shots","home":"5","away":"3","compareCode":1,"statisticsType":"negative","valueType":"event","homeValue":5,"awayValue":3,"renderType":1,"key":"blockedScoringAttempt"},{"name":"Shots inside box","home":"8","away":"11","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":8,"awayValue":11,"renderType":1,"key":"totalShotsInsideBox"},{"name":"Shots outside box","home":"7","away":"1","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":7,"awayValue":1,"renderType":1,"key":"totalShotsOutsideBox"}]},{"groupName":"Attack","statisticsItems":[{"name":"Big chances scored","home":"0","away":"3","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0,"awayValue":3,"renderType":1,"key":"bigChanceScored"},{"name":"Big chances missed","home":"0","away":"2","compareCode":2,"statisticsType":"negative","valueType":"event","homeValue":0,"awayValue":2,"renderType":1,"key":"bigChanceMissed"},{"name":"Through balls","home":"1","away":"2","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":1,"awayValue":2,"renderType":1,"key":"accurateThroughBall"},{"name":"Touches in penalty area","home":"36","away":"32","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":36,"awayValue":32,"renderType":1,"key":"touchesInOppBox"},{"name":"Fouled in final third","home":"3","away":"0","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":3,"awayValue":0,"renderType":1,"key":"fouledFinalThird"},{"name":"Offsides","home":"2","away":"1","compareCode":1,"statisticsType":"negative","valueType":"event","homeValue":2,"awayValue":1,"renderType":1,"key":"offsides"}]},{"groupName":"Passes","statisticsItems":[{"name":"Accurate passes","home":"444","away":"393","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":444,"awayValue":393,"renderType":1,"key":"accuratePasses"},{"name":"Throw-ins","home":"9","away":"8","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":9,"awayValue":8,"renderType":1,"key":"throwIns"},{"name":"Final third entries","home":"68","away":"37","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":68,"awayValue":37,"renderType":1,"key":"finalThirdEntries"},{"name":"Final third phase","home":"108\/144 (75%)","away":"68\/91 (75%)","compareCode":1,"statisticsType":"positive","valueType":"team","homeValue":108,"awayValue":68,"homeTotal":144,"awayTotal":91,"renderType":3,"key":"finalThirdPhaseStatistic"},{"name":"Long balls","home":"20\/35 (57%)","away":"23\/47 (49%)","compareCode":1,"statisticsType":"positive","valueType":"team","homeValue":20,"awayValue":23,"homeTotal":35,"awayTotal":47,"renderType":3,"key":"accurateLongBalls"},{"name":"Crosses","home":"6\/29 (21%)","away":"3\/8 (38%)","compareCode":2,"statisticsType":"positive","valueType":"team","homeValue":6,"awayValue":3,"homeTotal":29,"awayTotal":8,"renderType":3,"key":"accurateCross"}]},{"groupName":"Duels","statisticsItems":[{"name":"Duels","home":"45%","away":"55%","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":45,"awayValue":55,"renderType":2,"key":"duelWonPercent"},{"name":"Dispossessed","home":"8","away":"11","compareCode":2,"statisticsType":"negative","valueType":"event","homeValue":8,"awayValue":11,"renderType":1,"key":"dispossessed"},{"name":"Ground duels","home":"33\/75 (44%)","away":"42\/75 (56%)","compareCode":2,"statisticsType":"positive","valueType":"team","homeValue":33,"awayValue":42,"homeTotal":75,"awayTotal":75,"renderType":3,"key":"groundDuelsPercentage"},{"name":"Aerial duels","home":"10\/20 (50%)","away":"10\/20 (50%)","compareCode":3,"statisticsType":"positive","valueType":"team","homeValue":10,"awayValue":10,"homeTotal":20,"awayTotal":20,"renderType":3,"key":"aerialDuelsPercentage"},{"name":"Dribbles","home":"9\/20 (45%)","away":"6\/11 (55%)","compareCode":2,"statisticsType":"positive","valueType":"team","homeValue":9,"awayValue":6,"homeTotal":20,"awayTotal":11,"renderType":3,"key":"dribblesPercentage"}]},{"groupName":"Defending","statisticsItems":[{"name":"Tackles won","home":"38%","away":"47%","compareCode":2,"statisticsType":"positive","valueType":"team","homeValue":6,"awayValue":9,"homeTotal":16,"awayTotal":19,"renderType":4,"key":"wonTacklePercent"},{"name":"Total tackles","home":"16","away":"19","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":16,"awayValue":19,"renderType":1,"key":"totalTackle"},{"name":"Interceptions","home":"8","away":"8","compareCode":3,"statisticsType":"positive","valueType":"event","homeValue":8,"awayValue":8,"renderType":1,"key":"interceptionWon"},{"name":"Recoveries","home":"50","away":"49","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":50,"awayValue":49,"renderType":1,"key":"ballRecovery"},{"name":"Clearances","home":"10","away":"34","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":10,"awayValue":34,"renderType":1,"key":"totalClearance"}]},{"groupName":"Goalkeeping","statisticsItems":[{"name":"Total saves","home":"2","away":"7","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":2,"awayValue":7,"renderType":1,"key":"goalkeeperSaves"},{"name":"Goals prevented","home":"-0.27","away":"0.82","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":-0.2651,"awayValue":0.819,"renderType":1,"key":"goalsPrevented"},{"name":"Punches","home":"1","away":"2","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":1,"awayValue":2,"renderType":1,"key":"punches"},{"name":"Goal kicks","home":"4","away":"7","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":4,"awayValue":7,"renderType":1,"key":"goalKicks"}]}]},{"period":"1ST","groups":[{"groupName":"Match overview","statisticsItems":[{"name":"Ball possession","home":"50%","away":"50%","compareCode":3,"statisticsType":"positive","valueType":"event","homeValue":50,"awayValue":50,"renderType":2,"key":"ballPossession"},{"name":"Expected goals","home":"0.41","away":"0.93","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0.41,"awayValue":0.93,"renderType":1,"key":"expectedGoals"},{"name":"Big chances","home":"0","away":"3","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0,"awayValue":3,"renderType":1,"key":"bigChanceCreated"},{"name":"Total shots","home":"8","away":"5","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":8,"awayValue":5,"renderType":1,"key":"totalShotsOnGoal"},{"name":"Goalkeeper saves","home":"0","away":"3","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0,"awayValue":3,"renderType":1,"key":"goalkeeperSaves"},{"name":"Corner kicks","home":"4","away":"0","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":4,"awayValue":0,"renderType":1,"key":"cornerKicks"},{"name":"Passes","home":"232","away":"248","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":232,"awayValue":248,"renderType":1,"key":"passes"},{"name":"Tackles","home":"7","away":"7","compareCode":3,"statisticsType":"positive","valueType":"event","homeValue":7,"awayValue":7,"renderType":1,"key":"totalTackle"},{"name":"Free kicks","home":"6","away":"5","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":6,"awayValue":5,"renderType":1,"key":"freeKicks"},{"name":"Yellow cards","home":"0","away":"1","compareCode":2,"statisticsType":"negative","valueType":"event","homeValue":0,"awayValue":1,"renderType":1,"key":"yellowCards"}]},{"groupName":"Shots","statisticsItems":[{"name":"Total shots","home":"8","away":"5","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":8,"awayValue":5,"renderType":1,"key":"totalShotsOnGoal"},{"name":"Shots on target","home":"3","away":"2","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":3,"awayValue":2,"renderType":1,"key":"shotsOnGoal"},{"name":"Hit woodwork","home":"0","away":"0","compareCode":3,"statisticsType":"negative","valueType":"event","homeValue":0,"awayValue":0,"renderType":1,"key":"hitWoodwork"},{"name":"Shots off target","home":"3","away":"2","compareCode":1,"statisticsType":"negative","valueType":"event","homeValue":3,"awayValue":2,"renderType":1,"key":"shotsOffGoal"},{"name":"Blocked shots","home":"2","away":"1","compareCode":1,"statisticsType":"negative","valueType":"event","homeValue":2,"awayValue":1,"renderType":1,"key":"blockedScoringAttempt"},{"name":"Shots inside box","home":"6","away":"4","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":6,"awayValue":4,"renderType":1,"key":"totalShotsInsideBox"},{"name":"Shots outside box","home":"2","away":"1","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":2,"awayValue":1,"renderType":1,"key":"totalShotsOutsideBox"}]},{"groupName":"Attack","statisticsItems":[{"name":"Big chances scored","home":"0","away":"2","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0,"awayValue":2,"renderType":1,"key":"bigChanceScored"},{"name":"Big chances missed","home":"0","away":"1","compareCode":2,"statisticsType":"negative","valueType":"event","homeValue":0,"awayValue":1,"renderType":1,"key":"bigChanceMissed"},{"name":"Through balls","home":"0","away":"2","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0,"awayValue":2,"renderType":1,"key":"accurateThroughBall"},{"name":"Fouled in final third","home":"3","away":"0","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":3,"awayValue":0,"renderType":1,"key":"fouledFinalThird"},{"name":"Offsides","home":"2","away":"0","compareCode":1,"statisticsType":"negative","valueType":"event","homeValue":2,"awayValue":0,"renderType":1,"key":"offsides"}]},{"groupName":"Passes","statisticsItems":[{"name":"Accurate passes","home":"202","away":"217","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":202,"awayValue":217,"renderType":1,"key":"accuratePasses"},{"name":"Throw-ins","home":"4","away":"3","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":4,"awayValue":3,"renderType":1,"key":"throwIns"},{"name":"Final third entries","home":"32","away":"14","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":32,"awayValue":14,"renderType":1,"key":"finalThirdEntries"},{"name":"Long balls","home":"8\/15 (53%)","away":"14\/27 (52%)","compareCode":1,"statisticsType":"positive","valueType":"team","homeValue":8,"awayValue":14,"homeTotal":15,"awayTotal":27,"renderType":3,"key":"accurateLongBalls"},{"name":"Crosses","home":"4\/14 (29%)","away":"1\/1 (100%)","compareCode":2,"statisticsType":"positive","valueType":"team","homeValue":4,"awayValue":1,"homeTotal":14,"awayTotal":1,"renderType":3,"key":"accurateCross"}]},{"groupName":"Duels","statisticsItems":[{"name":"Duels","home":"59%","away":"41%","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":59,"awayValue":41,"renderType":2,"key":"duelWonPercent"},{"name":"Dispossessed","home":"4","away":"5","compareCode":2,"statisticsType":"negative","valueType":"event","homeValue":4,"awayValue":5,"renderType":1,"key":"dispossessed"},{"name":"Ground duels","home":"20\/33 (61%)","away":"13\/33 (39%)","compareCode":1,"statisticsType":"positive","valueType":"team","homeValue":20,"awayValue":13,"homeTotal":33,"awayTotal":33,"renderType":3,"key":"groundDuelsPercentage"},{"name":"Aerial duels","home":"6\/11 (55%)","away":"5\/11 (45%)","compareCode":1,"statisticsType":"positive","valueType":"team","homeValue":6,"awayValue":5,"homeTotal":11,"awayTotal":11,"renderType":3,"key":"aerialDuelsPercentage"},{"name":"Dribbles","home":"7\/10 (70%)","away":"1\/3 (33%)","compareCode":1,"statisticsType":"positive","valueType":"team","homeValue":7,"awayValue":1,"homeTotal":10,"awayTotal":3,"renderType":3,"key":"dribblesPercentage"}]},{"groupName":"Defending","statisticsItems":[{"name":"Tackles won","home":"29%","away":"57%","compareCode":2,"statisticsType":"positive","valueType":"team","homeValue":2,"awayValue":4,"homeTotal":7,"awayTotal":7,"renderType":4,"key":"wonTacklePercent"},{"name":"Total tackles","home":"7","away":"7","compareCode":3,"statisticsType":"positive","valueType":"event","homeValue":7,"awayValue":7,"renderType":1,"key":"totalTackle"},{"name":"Interceptions","home":"2","away":"5","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":2,"awayValue":5,"renderType":1,"key":"interceptionWon"},{"name":"Recoveries","home":"23","away":"20","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":23,"awayValue":20,"renderType":1,"key":"ballRecovery"},{"name":"Clearances","home":"0","away":"23","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0,"awayValue":23,"renderType":1,"key":"totalClearance"}]},{"groupName":"Goalkeeping","statisticsItems":[{"name":"Total saves","home":"0","away":"3","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0,"awayValue":3,"renderType":1,"key":"goalkeeperSaves"},{"name":"Goal kicks","home":"2","away":"5","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":2,"awayValue":5,"renderType":1,"key":"goalKicks"}]}]},{"period":"2ND","groups":[{"groupName":"Match overview","statisticsItems":[{"name":"Ball possession","home":"56%","away":"44%","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":56,"awayValue":44,"renderType":2,"key":"ballPossession"},{"name":"Expected goals","home":"0.45","away":"1.26","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0.45,"awayValue":1.26,"renderType":1,"key":"expectedGoals"},{"name":"Big chances","home":"0","away":"2","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0,"awayValue":2,"renderType":1,"key":"bigChanceCreated"},{"name":"Total shots","home":"7","away":"7","compareCode":3,"statisticsType":"positive","valueType":"event","homeValue":7,"awayValue":7,"renderType":1,"key":"totalShotsOnGoal"},{"name":"Goalkeeper saves","home":"2","away":"4","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":2,"awayValue":4,"renderType":1,"key":"goalkeeperSaves"},{"name":"Corner kicks","home":"2","away":"5","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":2,"awayValue":5,"renderType":1,"key":"cornerKicks"},{"name":"Passes","home":"266","away":"206","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":266,"awayValue":206,"renderType":1,"key":"passes"},{"name":"Tackles","home":"9","away":"12","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":9,"awayValue":12,"renderType":1,"key":"totalTackle"},{"name":"Free kicks","home":"3","away":"12","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":3,"awayValue":12,"renderType":1,"key":"freeKicks"},{"name":"Yellow cards","home":"5","away":"1","compareCode":1,"statisticsType":"negative","valueType":"event","homeValue":5,"awayValue":1,"renderType":1,"key":"yellowCards"}]},{"groupName":"Shots","statisticsItems":[{"name":"Total shots","home":"7","away":"7","compareCode":3,"statisticsType":"positive","valueType":"event","homeValue":7,"awayValue":7,"renderType":1,"key":"totalShotsOnGoal"},{"name":"Shots on target","home":"4","away":"3","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":4,"awayValue":3,"renderType":1,"key":"shotsOnGoal"},{"name":"Hit woodwork","home":"0","away":"0","compareCode":3,"statisticsType":"negative","valueType":"event","homeValue":0,"awayValue":0,"renderType":1,"key":"hitWoodwork"},{"name":"Shots off target","home":"0","away":"2","compareCode":2,"statisticsType":"negative","valueType":"event","homeValue":0,"awayValue":2,"renderType":1,"key":"shotsOffGoal"},{"name":"Blocked shots","home":"3","away":"2","compareCode":1,"statisticsType":"negative","valueType":"event","homeValue":3,"awayValue":2,"renderType":1,"key":"blockedScoringAttempt"},{"name":"Shots inside box","home":"2","away":"7","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":2,"awayValue":7,"renderType":1,"key":"totalShotsInsideBox"},{"name":"Shots outside box","home":"5","away":"0","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":5,"awayValue":0,"renderType":1,"key":"totalShotsOutsideBox"}]},{"groupName":"Attack","statisticsItems":[{"name":"Big chances scored","home":"0","away":"1","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":0,"awayValue":1,"renderType":1,"key":"bigChanceScored"},{"name":"Big chances missed","home":"0","away":"1","compareCode":2,"statisticsType":"negative","valueType":"event","homeValue":0,"awayValue":1,"renderType":1,"key":"bigChanceMissed"},{"name":"Through balls","home":"1","away":"0","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":1,"awayValue":0,"renderType":1,"key":"accurateThroughBall"},{"name":"Fouled in final third","home":"0","away":"0","compareCode":3,"statisticsType":"positive","valueType":"event","homeValue":0,"awayValue":0,"renderType":1,"key":"fouledFinalThird"},{"name":"Offsides","home":"0","away":"1","compareCode":2,"statisticsType":"negative","valueType":"event","homeValue":0,"awayValue":1,"renderType":1,"key":"offsides"}]},{"groupName":"Passes","statisticsItems":[{"name":"Accurate passes","home":"242","away":"176","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":242,"awayValue":176,"renderType":1,"key":"accuratePasses"},{"name":"Throw-ins","home":"5","away":"5","compareCode":3,"statisticsType":"positive","valueType":"event","homeValue":5,"awayValue":5,"renderType":1,"key":"throwIns"},{"name":"Final third entries","home":"36","away":"23","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":36,"awayValue":23,"renderType":1,"key":"finalThirdEntries"},{"name":"Long balls","home":"12\/20 (60%)","away":"9\/20 (45%)","compareCode":1,"statisticsType":"positive","valueType":"team","homeValue":12,"awayValue":9,"homeTotal":20,"awayTotal":20,"renderType":3,"key":"accurateLongBalls"},{"name":"Crosses","home":"2\/15 (13%)","away":"2\/7 (29%)","compareCode":2,"statisticsType":"positive","valueType":"team","homeValue":2,"awayValue":2,"homeTotal":15,"awayTotal":7,"renderType":3,"key":"accurateCross"}]},{"groupName":"Duels","statisticsItems":[{"name":"Duels","home":"33%","away":"67%","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":33,"awayValue":67,"renderType":2,"key":"duelWonPercent"},{"name":"Dispossessed","home":"4","away":"6","compareCode":2,"statisticsType":"negative","valueType":"event","homeValue":4,"awayValue":6,"renderType":1,"key":"dispossessed"},{"name":"Ground duels","home":"13\/42 (31%)","away":"29\/42 (69%)","compareCode":2,"statisticsType":"positive","valueType":"team","homeValue":13,"awayValue":29,"homeTotal":42,"awayTotal":42,"renderType":3,"key":"groundDuelsPercentage"},{"name":"Aerial duels","home":"4\/9 (44%)","away":"5\/9 (56%)","compareCode":2,"statisticsType":"positive","valueType":"team","homeValue":4,"awayValue":5,"homeTotal":9,"awayTotal":9,"renderType":3,"key":"aerialDuelsPercentage"},{"name":"Dribbles","home":"2\/10 (20%)","away":"5\/8 (63%)","compareCode":2,"statisticsType":"positive","valueType":"team","homeValue":2,"awayValue":5,"homeTotal":10,"awayTotal":8,"renderType":3,"key":"dribblesPercentage"}]},{"groupName":"Defending","statisticsItems":[{"name":"Tackles won","home":"44%","away":"42%","compareCode":1,"statisticsType":"positive","valueType":"team","homeValue":4,"awayValue":5,"homeTotal":9,"awayTotal":12,"renderType":4,"key":"wonTacklePercent"},{"name":"Total tackles","home":"9","away":"12","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":9,"awayValue":12,"renderType":1,"key":"totalTackle"},{"name":"Interceptions","home":"6","away":"3","compareCode":1,"statisticsType":"positive","valueType":"event","homeValue":6,"awayValue":3,"renderType":1,"key":"interceptionWon"},{"name":"Recoveries","home":"27","away":"29","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":27,"awayValue":29,"renderType":1,"key":"ballRecovery"},{"name":"Clearances","home":"10","away":"11","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":10,"awayValue":11,"renderType":1,"key":"totalClearance"}]},{"groupName":"Goalkeeping","statisticsItems":[{"name":"Total saves","home":"2","away":"4","compareCode":2,"statisticsType":"positive","valueType":"event","homeValue":2,"awayValue":4,"renderType":1,"key":"goalkeeperSaves"},{"name":"Goal kicks","home":"2","away":"2","compareCode":3,"statisticsType":"positive","valueType":"event","homeValue":2,"awayValue":2,"renderType":1,"key":"goalKicks"}]}]}]}

**Comment by yssefunc** [comment]
Hi,  
I tried it, and it worked. Was there any change, or was the error caused by an unknown bug?

**Comment by oseymour** [comment]
No, I haven't made any changes. But I don't know if you've upgraded?

But yeah I think this was just a random error. Somehow Sofascore detected your scraping and just refused the request. Had you been scraping really heavily before this happened?

**Comment by yssefunc** [comment]
I do not perform any upgrades. No, I have not used it heavily before.

**Comment by oseymour** [comment]
Yeah that's weird. Maybe their API was down for a bit or something. I'm going to close this but if this crops up again please reopen it. I can try to reproduce it.
