### ISSUE TITLE
Corner Case for Fotmob's Shot Scraping Sorting

### ISSUE THREAD

**Issue by hedonistrh** [oseymour/ScraperFC#5]
Hey Owen, I am still working on Fotmob scraper as well. While doing that, also checked your code. And realized that, in the current implementation, you are getting minute of the shot [here](https://github.com/oseymour/ScraperFC/blob/main/code/ScraperFC/FotMob.py#L109-L113) and doing bit post-processing. So it can deal with addition time. (if i understand correctly **45+3** become **48** there) Then sorting shots by **minutes** [here](https://github.com/oseymour/ScraperFC/blob/main/code/ScraperFC/FotMob.py#L160). 

However, that can cause not-fully correct ordering if i am not missing anything. Because with that sorting, a shot happening at the 46' will happen before than 45+2' one. That is actually corner case but just would like to mention that. 😅 

I know that is still in development _(and maybe you already modified that)_ but in case you missed that part. 🗒️

**Comment by oseymour** [comment]
Yeah I haven't finished that code up yet. I was planning on removing that, just added it for troubleshooting during dev. Thanks!
