### ISSUE TITLE
Oddsportal module not recognized

### ISSUE THREAD

**Issue by Tomas61692** [oseymour/ScraperFC#51]
Question:
any reason why Oddsportal class is not being recognized?
im not having problem with the other modules.

![image](https://github.com/user-attachments/assets/ba8af287-39de-4476-80ea-5fc5f86f3ce3)

![image](https://github.com/user-attachments/assets/9f114415-acdd-4d68-a825-fa15a0bbab16)

thanks in advance Owen!

**Comment by oseymour** [comment]
It's not supposed to be include. It's not imported in __init__.py because I never finished it.

**Comment by Tomas61692** [comment]
that was the last thing i thought of in my impatience. 
thanks Owen.
any tentative date for its completion?

**Comment by oseymour** [comment]
To be honest, I was going to remove the oddsportal.py file soon. I never really figured out a stable way to scrape it and I'm not sure there's a lot of interest in it.

Not to say it wouldn't be a possibility in the future. But just hasn't been a priority lately.

**Comment by oseymour** [comment]
Removed Oddsportal.py in the latest commit.
